name: Trigger Quartz Build

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # Must be an org secret with repo scope on the Quartz repo
          token: ${{ secrets.ORG_LINUX_WIKI }}
          # Your Quartz repo
          repository: Open-Source-Community/quartz-repo
          event-type: content_updated
