name: Trigger Quartz Build

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # This token must be your Org Secret
          token: ${{ secrets.ORG_LINUX_WIKI }}
          # Replace with your actual Org and Repo names
          repository:     Open-Source-Community/quartz-repo
          event-type: content_updated
